FOUNDATIONS: Modify Menu
Mums-Who-Code/MenuApp pull request #27
Opened 2022-05-11 18:35 UTC by NaynaMallick

2022-05-11 19:13 UTC, ShriHumrudha requested changes

2022-05-11 19:13 UTC, ShriHumrudha commented on MenuApp.Tests.Unit/Services/Foundations/Menus/MenuServiceTests.Logic.Modify.cs
> +                    .Returns(epectedMenu);
modifiedMenu?

2022-05-11 21:16 UTC, NaynaMallick commented on MenuApp.Tests.Unit/Services/Foundations/Menus/MenuServiceTests.Logic.Modify.cs
> +                    .Returns(epectedMenu);
modified

2022-05-13 01:12 UTC, ShriHumrudha approved these changes

2022-05-13 01:12 UTC, merged